# Generated by Django 3.2.8 on 2022-05-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('shape', models.CharField(max_length=5)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='recommondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('product_id', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('dob', models.DateField(null=True)),
                ('company', models.CharField(max_length=55)),
                ('mobile', models.IntegerField(help_text='Must include international prefix - e.g. +1 555 555 55555')),
                ('city', models.CharField(blank=True, max_length=55, null=True)),
                ('is_hr', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
    ]
